version: "3.9"

services:
    web:
        build: .
        container_name: order-store
        ports:
            - "80:80"
        volumes:
            - /home/system0xff/flaviao_projects/order-store:/var/www/html/
        links:
            - db

    db:
        image: postgres:latest
        container_name: order-store-pgsql
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgres
        environment:
            POSTGRES_USER: dbuser
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: orderstoredb
